In [10]:
import pandas as pd
import sys
import os
import numpy as np

FIELDS = ["jobid", "jobidraw", "cluster", "partition",
          "account", "group", "gid", "user", "uid",
          "submit", "eligible", "start", "end",
          "elapsed", "exitcode", "state", "nnodes",
          "ncpus", "reqcpus", "reqmem", "reqgres",
          "reqtres", "timelimit", "nodelist",
          "jobname"]

In [11]:
rootdir='sacct_outputs'
# rootdir2='sacct_outputs_no_dupes'
csvfile=os.path.join(rootdir, 'df_eligible_less_submit.csv')
df = pd.read_csv(csvfile,
                 parse_dates=[9, 10, 11, 12],
                 infer_datetime_format=True,
                 header=None,
                 delimiter='|',
                 engine='c',
                 # converters={'elapsed': d_h_m_s_to_timedelta},
                 #converters={'elapsed': reformat_timedelta_string,
                 #            'timelimit': reformat_timedelta_string},
                 names=FIELDS)

In [17]:
df['el-sub'] = df['eligible']-df['submit'];
df['st-el'] = df['start']-df['eligible'];
df['st-sub'] = df['start']-df['submit'];
df[['jobid','submit','eligible','start','el-sub','st-el','st-sub']]

,jobid,submit,eligible,start,el-sub,st-el,st-sub
0,316,2015-07-01 14:21:33,2015-06-28 18:15:06,2015-07-02 10:47:53,-3 days +03:53:33,3 days 16:32:47,0 days 20:26:20
1,316,2015-07-02 12:23:13,2015-06-28 18:15:06,2015-07-03 17:48:57,-4 days +05:51:53,4 days 23:33:51,1 days 05:25:44
2,479,2011-06-01 22:28:43,2011-06-01 22:28:33,2011-06-01 22:29:05,-1 days +23:59:50,0 days 00:00:32,0 days 00:00:22
3,479,2011-06-01 22:29:29,2011-06-01 22:28:33,2011-06-01 22:29:42,-1 days +23:59:04,0 days 00:01:09,0 days 00:00:13
4,480,2011-06-01 22:35:09,2011-06-01 22:34:35,2011-06-01 22:35:09,-1 days +23:59:26,0 days 00:00:34,0 days 00:00:00
5,481,2011-06-01 22:53:14,2011-06-01 22:52:37,2011-06-01 22:53:14,-1 days +23:59:23,0 days 00:00:37,0 days 00:00:00
6,581,2011-06-02 18:14:12,2011-06-02 14:07:18,2011-06-02 20:38:59,-1 days +19:53:06,0 days 06:31:41,0 days 02:24:47
7,582,2011-06-02 18:14:12,2011-06-02 14:18:58,2011-06-02 20:38:59,-1 days +20:04:46,0 days 06:20:01,0 days 02:24:47
8,583,2015-07-06 15:36:44,2015-07-05 23:06:33,2015-07-06 15:36:45,-1 days +07:29:49,0 days 16:30:12,0 days 00:00:01
9,588,2011-06-02 18:14:12,2011-06-02 16:09:25,2011-06-02 20:38:59,-1 days +21:55:13,0 days 04:29:34,0 days 02:24:47
10,589,2011-06-02 18:06:34,2011-06-02 16:42:48,2011-06-02 20:38:49,-1 days +22:36:14,0 days 03:56:01,0 days 02:32:15
11,590,2011-06-02 18:06:37,2011-06-02 16:48:18,2011-06-02 20:38:59,-1 days +22:41:41,0 days 03:50:41,0 days 02:32:22
12,591,2011-06-02 18:06:37,2011-06-02 16:53:06,2011-06-02 20:38:59,-1 days +22:46:29,0 days 03:45:53,0 days 02:32:22
13,767,2011-06-15 12:47:59,2011-06-15 12:06:20,2011-06-15 12:48:00,-1 days +23:18:21,0 days 00:41:40,0 days 00:00:01
14,788,2015-07-14 16:34:15,2015-07-13 11:58:09,2015-07-14 16:34:16,-2 days +19:23:54,1 days 04:36:07,0 days 00:00:01
15,2154,2015-08-19 19:21:17,2015-08-18 16:29:10,2015-08-19 19:22:27,-2 days +21:07:53,1 days 02:53:17,0 days 00:01:10
16,2157,2015-08-19 19:21:17,2015-08-18 16:47:03,2015-08-19 19:21:19,-2 days +21:25:46,1 days 02:34:16,0 days 00:00:02
17,2161,2015-08-19 19:21:17,2015-08-18 17:57:09,2015-08-19 19:22:27,-2 days +22:35:52,1 days 01:25:18,0 days 00:01:10
18,2162,2015-08-19 19:21:17,2015-08-18 17:57:10,2015-08-19 19:22:27,-2 days +22:35:53,1 days 01:25:17,0 days 00:01:10
19,2168,2015-08-19 19:21:17,2015-08-18 19:08:30,2015-08-19 20:24:18,-2 days +23:47:13,1 days 01:15:48,0 days 01:03:01
20,2338,2015-08-30 16:09:29,2015-08-27 11:59:53,2015-09-01 05:24:05,-4 days +19:50:24,4 days 17:24:12,1 days 13:14:36
21,2560,2015-09-05 15:36:34,2015-09-02 17:57:08,2015-09-05 15:36:35,-3 days +02:20:34,2 days 21:39:27,0 days 00:00:01
22,2594,2015-09-09 12:42:52,2015-09-04 21:46:29,2015-09-09 15:34:28,-5 days +09:03:37,4 days 17:47:59,0 days 02:51:36
23,2605,2015-09-05 15:36:34,2015-09-05 13:51:16,2015-09-05 15:36:34,-1 days +22:14:42,0 days 01:45:18,0 days 00:00:00
24,2847,2015-09-15 16:04:53,2015-09-12 00:10:16,2015-09-18 00:35:37,-4 days +08:05:23,6 days 00:25:21,2 days 08:30:44
25,2872,2015-09-15 16:06:33,2015-09-15 00:47:59,2015-09-18 00:35:37,-1 days +08:41:26,2 days 23:47:38,2 days 08:29:04
26,2878,2015-09-15 16:06:33,2015-09-15 00:56:09,2015-09-18 00:37:04,-1 days +08:49:36,2 days 23:40:55,2 days 08:30:31
27,5089,2015-10-19 11:09:11,2015-10-05 17:32:25,2015-10-19 11:09:12,-14 days +06:23:14,13 days 17:36:47,0 days 00:00:01
28,5898,2015-10-30 16:59:35,2015-10-29 14:56:57,2015-10-30 16:59:48,-2 days +21:57:22,1 days 02:02:51,0 days 00:00:13
29,5978,2015-11-03 09:01:17,2015-11-03 08:50:39,2015-11-03 09:02:57,-1 days +23:49:22,0 days 00:12:18,0 days 00:01:40
...,...,...,...,...,...,...,...
1666,2541929,2015-04-01 03:48:34,2015-03-31 11:36:25,2015-04-01 03:48:35,-1 days +07:47:51,0 days 16:12:10,0 days 00:00:01
1667,2541929,2015-04-01 11:48:35,2015-03-31 11:36:25,2015-04-01 11:49:37,-2 days +23:47:50,1 days 00:13:12,0 days 00:01:02
1668,2542652,2015-04-14 19:57:44,2015-04-14 19:48:35,2015-04-14 20:23:45,-1 days +23:50:51,0 days 00:35:10,0 days 00:26:01
1669,2542652,2015-04-14 20:34:24,2015-04-14 19:48:35,2015-04-14 21:08:43,-1 days +23:14:11,0 days 01:20:08,0 days 00:34:19
1670,2542652,2015-04-14 21:19:24,2015-04-14 19:48:35,2015-04-15 02:37:11,-1 days +22:29:11,0 days 06:48:36,0 days 05:17:47
1671,2542653,2015-04-14 19:57:44,2015-04-14 19:48:38,2015-04-14 20:35:35,-1 days +23:50:54,0 days 00:46:57,0 days 00:37:51
1672,2542653,2015-04-14 20:44:24,2015-04-14 19:48:38,2015-04-14 21:09:02,-1 days +23:04:14,0 days 01:20:24,0 days 00:24:38
1673,2542653,2015-04-14 21:19:24,2015-04-14 19:48:38,2015-04-15 02:36:42,-1 days +22:29:14,0 days 06:48:04,0 days 05:17:18
1674,2542654,2015-04-14 20:11:04,2015-04-14 19:48:47,2015-04-14 20:35:35,-1 days +23:37:43,0 days 00:46:48,0 days 00:24:31
1675,2542654,2015-04-14 20:44:24,2015-04-14 19:48:47,2015-04-14 21:20:04,-1 days +23:04:23,0 days 01:31:17,0 days 00:35:40
1676,2542654,2015-04-14 21:29:24,2015-04-14 19:48:47,2015-04-15 02:55:28,-1 days +22:19:23,0 days 07:06:41,0 days 05:26:04
1677,2542655,2015-04-14 20:11:04,2015-04-14 19:48:50,2015-04-14 20:46:48,-1 days +23:37:46,0 days 00:57:58,0 days 00:35:44
1678,2542655,2015-04-14 20:56:06,2015-04-14 19:48:50,2015-04-14 21:54:04,-1 days +22:52:44,0 days 02:05:14,0 days 00:57:58
1679,2542656,2015-04-14 20:22:44,2015-04-14 19:49:00,2015-04-14 20:47:02,-1 days +23:26:16,0 days 00:58:02,0 days 00:24:18
1680,2542656,2015-04-14 20:56:04,2015-04-14 19:49:00,2015-04-14 21:54:04,-1 days +22:52:56,0 days 02:05:04,0 days 00:58:00
1681,2542657,2015-04-14 20:22:44,2015-04-14 19:49:04,2015-04-14 20:57:34,-1 days +23:26:20,0 days 01:08:30,0 days 00:34:50
1682,2542657,2015-04-14 21:06:04,2015-04-14 19:49:04,2015-04-15 01:56:59,-1 days +22:43:00,0 days 06:07:55,0 days 04:50:55
1683,2542658,2015-04-14 20:34:24,2015-04-14 19:49:11,2015-04-14 20:57:34,-1 days +23:14:47,0 days 01:08:23,0 days 00:23:10
1684,2542658,2015-04-14 21:06:04,2015-04-14 19:49:11,2015-04-15 01:58:01,-1 days +22:43:07,0 days 06:08:50,0 days 04:51:57
1685,2542678,2015-04-14 21:29:24,2015-04-14 20:53:43,2015-04-15 03:04:40,-1 days +23:24:19,0 days 06:10:57,0 days 05:35:16
1686,2542679,2015-04-14 21:41:04,2015-04-14 20:53:45,2015-04-15 03:31:33,-1 days +23:12:41,0 days 06:37:48,0 days 05:50:29
1687,2542680,2015-04-14 21:41:04,2015-04-14 20:53:51,2015-04-15 04:01:52,-1 days +23:12:47,0 days 07:08:01,0 days 06:20:48
1688,2542681,2015-04-14 21:51:04,2015-04-14 20:54:01,2015-04-15 06:32:11,-1 days +23:02:57,0 days 09:38:10,0 days 08:41:07
1689,2542682,2015-04-14 21:51:04,2015-04-14 20:54:05,2015-04-15 08:05:23,-1 days +23:03:01,0 days 11:11:18,0 days 10:14:19
1690,2545225,2015-05-21 16:48:03,2015-05-21 11:13:26,2015-05-22 11:29:50,-1 days +18:25:23,1 days 00:16:24,0 days 18:41:47
1691,2545226,2015-05-21 16:51:23,2015-05-21 11:14:10,2015-05-22 11:29:51,-1 days +18:22:47,1 days 00:15:41,0 days 18:38:28
1692,2545227,2015-05-22 17:47:33,2015-05-21 11:14:42,2015-05-22 17:47:41,-2 days +17:27:09,1 days 06:32:59,0 days 00:00:08
1693,2545228,2015-05-22 17:47:33,2015-05-21 11:15:04,2015-05-22 17:47:50,-2 days +17:27:31,1 days 06:32:46,0 days 00:00:17
1694,2545566,2015-06-02 18:26:14,2015-06-02 14:31:18,2015-06-02 18:26:15,-1 days +20:05:04,0 days 03:54:57,0 days 00:00:01
1695,2545567,2015-06-02 18:26:14,2015-06-02 14:33:13,2015-06-02 18:53:29,-1 days +20:06:59,0 days 04:20:16,0 days 00:27:15